/**
* This file was automatically generated by cosmwasm-typescript-gen@0.2.14.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the cosmwasm-typescript-gen generate command to regenerate this file.
*/
import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { Coin } from "@cosmjs/amino";
export interface ClaimMessage {
    contractAddress: string;
    sender: string;
    claimMintNft: ({ minterAddress }: {
        minterAddress: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    saleHook: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    updateAdmin: ({ admin }: {
        admin?: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    updateMarketplace: ({ marketplaceAddr }: {
        marketplaceAddr?: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class ClaimMessageComposer implements ClaimMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    claimMintNft: ({ minterAddress }: {
        minterAddress: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    saleHook: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    updateAdmin: ({ admin }: {
        admin?: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    updateMarketplace: ({ marketplaceAddr }: {
        marketplaceAddr?: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
}
