/**
* This file was automatically generated by cosmwasm-typescript-gen@0.2.14.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the cosmwasm-typescript-gen generate command to regenerate this file.
*/
import { CosmWasmClient, ExecuteResult, SigningCosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
export interface AdminResponse {
    admin?: string | null;
    [k: string]: unknown;
}
export interface HooksResponse {
    hooks: string[];
    [k: string]: unknown;
}
export interface InstantiateMsg {
    admin?: string | null;
    members: Member[];
    [k: string]: unknown;
}
export interface Member {
    addr: string;
    weight: number;
    [k: string]: unknown;
}
export interface ListMembersResponse {
    members: Member[];
    [k: string]: unknown;
}
export interface MemberListResponse {
    members: Member[];
    [k: string]: unknown;
}
export interface MemberResponse {
    weight?: number | null;
    [k: string]: unknown;
}
export interface TotalWeightResponse {
    weight: number;
    [k: string]: unknown;
}
export interface RoyaltyGroupReadOnlyInterface {
    contractAddress: string;
    admin: () => Promise<AdminResponse>;
    totalWeight: () => Promise<TotalWeightResponse>;
    listMembers: ({ limit, startAfter }: {
        limit?: number;
        startAfter?: string;
    }) => Promise<ListMembersResponse>;
    member: ({ addr, atHeight }: {
        addr: string;
        atHeight?: number;
    }) => Promise<MemberResponse>;
    hooks: () => Promise<HooksResponse>;
}
export declare class RoyaltyGroupQueryClient implements RoyaltyGroupReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    admin: () => Promise<AdminResponse>;
    totalWeight: () => Promise<TotalWeightResponse>;
    listMembers: ({ limit, startAfter }: {
        limit?: number;
        startAfter?: string;
    }) => Promise<ListMembersResponse>;
    member: ({ addr, atHeight }: {
        addr: string;
        atHeight?: number;
    }) => Promise<MemberResponse>;
    hooks: () => Promise<HooksResponse>;
}
export interface RoyaltyGroupInterface extends RoyaltyGroupReadOnlyInterface {
    contractAddress: string;
    sender: string;
    updateAdmin: ({ admin }: {
        admin?: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: readonly Coin[]) => Promise<ExecuteResult>;
    updateMembers: ({ add, remove }: {
        add: Member[];
        remove: string[];
    }, fee?: number | StdFee | "auto", memo?: string, funds?: readonly Coin[]) => Promise<ExecuteResult>;
    addHook: ({ addr }: {
        addr: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: readonly Coin[]) => Promise<ExecuteResult>;
    removeHook: ({ addr }: {
        addr: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: readonly Coin[]) => Promise<ExecuteResult>;
    distribute: ({ funds }: {
        funds: Coin;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: readonly Coin[]) => Promise<ExecuteResult>;
}
export declare class RoyaltyGroupClient extends RoyaltyGroupQueryClient implements RoyaltyGroupInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    updateAdmin: ({ admin }: {
        admin?: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: readonly Coin[]) => Promise<ExecuteResult>;
    updateMembers: ({ add, remove }: {
        add: Member[];
        remove: string[];
    }, fee?: number | StdFee | "auto", memo?: string, funds?: readonly Coin[]) => Promise<ExecuteResult>;
    addHook: ({ addr }: {
        addr: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: readonly Coin[]) => Promise<ExecuteResult>;
    removeHook: ({ addr }: {
        addr: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: readonly Coin[]) => Promise<ExecuteResult>;
    distribute: ({ funds }: {
        funds: Coin;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: readonly Coin[]) => Promise<ExecuteResult>;
}
