/**
* This file was automatically generated by cosmwasm-typescript-gen@0.2.14.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the cosmwasm-typescript-gen generate command to regenerate this file.
*/
import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { Coin } from "@cosmjs/amino";
import { Member } from "./RoyaltyGroupContract";
export interface RoyaltyGroupMessage {
    contractAddress: string;
    sender: string;
    updateAdmin: ({ admin }: {
        admin?: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    updateMembers: ({ add, remove }: {
        add: Member[];
        remove: string[];
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    addHook: ({ addr }: {
        addr: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    removeHook: ({ addr }: {
        addr: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    distribute: ({ funds }: {
        funds: Coin;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class RoyaltyGroupMessageComposer implements RoyaltyGroupMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    updateAdmin: ({ admin }: {
        admin?: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    updateMembers: ({ add, remove }: {
        add: Member[];
        remove: string[];
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    addHook: ({ addr }: {
        addr: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    removeHook: ({ addr }: {
        addr: string;
    }, funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    distribute: ({ funds }: {
        funds: Coin;
    }, _funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
}
