/**
* This file was automatically generated by cosmwasm-typescript-gen@0.2.14.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the cosmwasm-typescript-gen generate command to regenerate this file.
*/
import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { Coin } from "./WhitelistContract";
export interface WhitelistMessage {
    contractAddress: string;
    sender: string;
    updateStartTime: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    updateEndTime: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    addMembers: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    removeMembers: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    updatePerAddressLimit: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    increaseMemberLimit: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class WhitelistMessageComposer implements WhitelistMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    updateStartTime: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    updateEndTime: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    addMembers: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    removeMembers: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    updatePerAddressLimit: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
    increaseMemberLimit: (funds?: readonly Coin[]) => MsgExecuteContractEncodeObject;
}
